permissions:
  contents: write
  
name: Update NeoDB Data

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Create data directory
        run: mkdir -p data
      
      - name: Fetch NeoDB data
        env:
          NEODB_USERNAME: ${{ secrets.NEODB_USERNAME }}
        run: python scripts/fetch_neodb_data.py
      
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          
          # Check if there are changes
          if [[ -n $(git status -s data/) ]]; then
            git add data/neodb-data.json
            git commit -m "📊 Update NeoDB media data [skip ci]"
            git push
          else
            echo "No changes to NeoDB data"
          fi
